name: dds-v2
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.9.13
  - tensorflow
  - flask
  - munch
  - networkx
  - pyyaml
  - requests
  - pip
  - pip:
    - opencv-contrib-python
    - ultralytics
 

